# Info
baseURL = 'https://hosts.aao.fyi/'
languageCode = 'en'
title = 'Hosts'
copyright = 'aao.fyi'

# Theme
# Replace 'gitlab.com' with 'github.com' if error loading
theme = 'codeberg.org/aao-fyi/shock'

# Features
disableHugoGeneratorInject = false
disableKinds = ['RSS','taxonomy','term']
enableGitInfo = true
enableRobotsTXT = true

# Minify
[minify]
  minifyOutput = true

# Build
[build]
  # PostCSS
  writeStats = true

# Module
[module]
  # Version
  [module.hugoVersion]
    extended = true
    min = '0.128.0'
  # Hosts
  [[module.imports]]
    path = 'codeberg.org/aao-fyi/hosts'
  [[module.imports.mounts]]
    source = 'static/'
    target = 'static/'
  [[module.imports.mounts]]
    source = 'README.md'
    target = 'assets/README.md'
  # Logo
  [[module.imports]]
    path = 'codeberg.org/aao-fyi/project-logos'
  [[module.imports.mounts]]
    source = 'hosts/'
    target = 'assets/img/logo/'

[menu]
  # Connect
  [[menu.connect]]
    identifier = 'codeberg'
    name = 'Codeberg'
    weight = '10'
    color = '#2185d0'
    url = 'https://codeberg.org/aao-fyi/hosts'
  [[menu.connect]]
    identifier = 'github'
    name = 'GitHub'
    weight = '20'
    color = '#4078c0'
    url = 'https://github.com/aao-fyi/hosts'
  [[menu.connect]]
    identifier = 'gitlab'
    name = 'GitLab'
    weight = '15'
    color = '#fc6d26'
    url = 'https://gitlab.com/aao-fyi/hosts'
  # Footer
  [[menu.footer]]
    identifier = 'privacy'
    name = 'Privacy'
    url = 'https://aao.fyi/privacy/'
  [[menu.footer]]
    identifier = 'sitemap'
    name = 'Sitemap'
    url = '/sitemap.xml'
